#1) show that csc(x)*tan(x)==sec(x)
show(bool(csc(x)*tan(x)==sec(x)))
show(plot(csc(x)*tan(x)))
show(plot(sec(x)))
#2) show that (1+tan(x))/(1+cot(x))==tan(x)
show(bool((1+tan(x))/(1+cot(x))==tan(x)))
show(plot((1+tan(x))/(1+cot(x))))
show(plot(tan(x)))
#3) show that sin(x)^2+cos(x)^2==1
show(bool(sin(x)^2+cos(x)^2==1))
show(plot(sin(x)^2+cos(x)^2))
