#MrG 2018.1009 pre501 What's An Inverse Function?
show("#1) find the inverse of y==x^3")
var('y')
equ=x==y^3;show(equ)
equ=equ^(1/3);show(equ.canonicalize_radical())
show(plot([x^3,x,x^(1/3)],0,2,aspect_ratio=1))
show("")

show("#2) show that f(x)=3*x and g(x)=x/3 are inverses")
f(x)=3*x;show(f(x))
g(x)=x/3;show(g(x))
h(x)=f(g(x));show(h(x))
h(x)=g(f(x));show(h(x))
show(plot([f(x),h(x),g(x)],-4,2,aspect_ratio=1))
show()

show("#3) show that f(x)=2*x+3 and g(x)=(x-3)/2 are inverses")
f(x)=2*x+3;show(f(x))
g(x)=(x-3)/2;show(g(x))
h(x)=f(g(x));show(h(x))
h(x)=g(f(x));show(h(x))
show(plot([f(x),h(x),g(x)],-4,2,aspect_ratio=1))
show("")

show("#4) find the point of intersection of POI of F=(9/5)C+32 and its inverse function")
f(x)=(9/5)*x+32;show("f(x)=",f(x))
equ=x==(9/5)*y+32;show("f^(-1):",equ)
show(solve(equ,y))
show(solve((9/5)*x+32==(5/9)*(x-32),x))
plot([(9/5)*x+32,x,(5/9)*(x-32)],-50,0)
