#MrG 2018.0823 pre206 Modeling
show("#1a) The perimeter of a rectangle is 50 ft. If the width is x, find the with y as a function of x")
show("#1b) State the area of the rectangle as a function of x and find the maximum area, A(x).")
var('y')
show(solve(2*x+2*y==50,y))
A(x)=x*(25-x)
show("A(x)=",A(x).expand())
show(plot(A(x),0,25))
x=-25/(2*(-1))
show("axis of symmetry: x=",x.n())
show("Amax=",A(x).n())
show("")

show("#3 p162) Let p(x)=-x/6+100 for 0<=x<=600 be a demand function giving price per widget. [p]=$ and [x]=widgets")
show("3a p162) What is the revenue function R(x)?")
show("3b p162) If 200 wigets are sold, what is the price point and the revenue in $?")
show("3c p162) Graph the revenue function R(x).")
show("3d p162) What value of x will maximize R. Find Rmax?")
show("3e p162) What price should this factory set for each widget to maximize R?")
p(x)=-x/6+100;show("p(x)=",p(x));show("p(200)=",p(200).n())
R(x)=x*p(x);show("R(x)=",R(x));show("R(200)=",R(200).n())
plot(R(x),0,600)
show("R(x)=",R(x).expand())
x=-100/(2*(-1/6))
show("number of widgets to sell: ",x)
show("Rmax=$",R(x))
show("Optimum price point=$",p(x))
