#MrG 2018.1015 pre504 What Are Log Properties?
show("#1) log properties!")
show(log(1))
show(log(e))
show(log(e^2))
show(log(2*3).n())
show((log(2)+log(3)).n())
show(log(8/2).n())
show((log(8)-log(2)).n())
show(log(2^3).n())
show(3*log(2).n())
show("")
show("#2) simpify logs!")
show((log(x*sqrt(x^2+1))).canonicalize_radical())
show((log(x^2/(x-1)^3)).canonicalize_radical())
show((log(x^3*sqrt(x^2+1)/(x+1)^4)).canonicalize_radical())