#1) v.dot_product(w)=vx*wx+vy*wy
v=vector([2,-3])
w=vector([5,3])
show(v)
show(w)
show(v.dot_product(w))
#2) T/F v.dot_product(w)=w.dot_product(v)=wx*vx+wy*vy
show(w.dot_product(v))
#3) T/F abs(v)=sqrt(v.dot_product(v))
show(abs(v))
show(sqrt(v.dot_product(v)))
#4) T/F abs(w)=sqrt(w.dot_product(w))
show(abs(w))
show(sqrt(w.dot_product(w)))
#5) v.dot_product(w)=abs(v)*abs(w)*cos(t), find t!
v=vector([4,-3])
w=vector([2,5])
d=v.dot_product(w)
show(d)
show(d/abs(v)/abs(w))
show(arccos(d/abs(v)/abs(w)).n())
show((arccos(d/abs(v)/abs(w))*180/pi).n())
a=plot(v)
b=plot(w)
show(a+b,aspect_ratio=1)