#9 p629 find the area of the parallelogram formed by v and w
#9 p629 given v=<2,-3,1> and w=<3,-2,-1>
v=vector([2,-3,1])
w=vector([3,-2,-1])
c=v.cross_product(w)
show(v)
show(w)
show(c)
show(abs(c))
p1=plot(v,color='red')
p2=plot(w,color='green')
p3=plot(c,color='cyan')
show(p1+p2+p3,viewer='tachyon',aspect_ratio=1)
#31 p629 find the volume of the parallelopiped formed by v,u,w
#31 p629 such that v=<-3,3,2>, u=<2,-3,1>, w=<1,1,3>
#31) p629 ie: find v(uxw)
v=vector([-3,3,2])
u=vector([2,-3,1])
w=vector([1,1,3])
c=u.cross_product(w)
s=v.dot_product(c)
show(v)
show(u)
show(w)
show(c)
show(s)
p1=plot(u,color='red')
p2=plot(w,color='green')
p3=plot(c,color='cyan')
show(p1+p2+p3,viewer='tachyon',aspect_ratio=1)
#39) p629 v.cross_product(w)=abs(v)*abs(w)*sin(t)
#39) p629 find t given v=<1,2,3,> and w=<-2,3,0>
v=vector([1,2,3])
w=vector([-2,3,0])
c=v.cross_product(w)
show(abs(c))
show(abs(c)/abs(v)/abs(w))
show(arcsin(abs(c)/abs(v)/abs(w)).n())
show((arcsin(abs(c)/abs(v)/abs(w))*180/pi).n())
p1=plot(v,color='red')
p2=plot(w,color='green')
p3=plot(c,color='cyan')
show(p1+p2+p3,viewer='tachyon',aspect_ratio=1)