#MrG 2018.0905 UNIT 201: Limits
show("#1) Find the following limits at a point:")
var('c')
show(lim(x+4,x=-3))
show(lim(x+4,x=0))
show(lim(x+4,x=c))
plot(x+4,-4,0)
show(lim(2*x^2,x=1))
show(lim(2*x^2,x=-2))
show(lim(2*x^2,x=c))
plot(2*x^2,-2,2)
show("")

show("#2) Find the following limits at a point:")
f(x)=(x^2+2*x+4)/(x+2);show("f(x)=",f(x));show("f(x)=",f(x).partial_fraction())
show(lim(f(x),x=-2))
plot(f(x),xmin=-4,xmax=0,ymin=-10,ymax=10)
f(x)=(x^2+4*x+4)/(x+2);show("f(x)=",f(x));show("f(x)=",f(x).partial_fraction())
show(lim(f(x),x=-2))
plot(f(x),-4,0)
f(x)=(x^3+2*x+4)/(x+2);show("f(x)=",f(x));show("f(x)=",f(x).partial_fraction())
show(lim(f(x),x=-2))
plot(f(x),xmin=-10,xmax=10,ymin=-10,ymax=10)
show("")

show("#3) Find the following limits at infinity:")
f(x)=(2*x+1)/(3*x-2);show("f(x)=",f(x))
show(lim(f(x),x=infinity))
show(lim(f(x),x=-infinity))
plot(f(x),xmin=-100,xmax=100,ymin=0,ymax=1)
f(x)=(2*x^2+1)/(3*x-2);show("f(x)=",f(x))
show(lim(f(x),x=infinity))
show(lim(f(x),x=-infinity))
f(x)=(2*x+1)/(3*x^3-2);show("f(x)=",f(x))
show(lim(f(x),x=infinity))
show(lim(f(x),x=-infinity))
show("")

show("#4) Consider the piecewise defined function")
f1(x)=x+3 
f2(x)=-2*x-2 
f3(x)=x^2-1 
f4(x)=sqrt(1-(x-2)^2) 
f=piecewise([[(-4,-2),f1],[(-2,-1),f2],[(-1,1),f3],[(1,3),f4]]) 
show(lim(f1(x),x=-2,dir='left')) 
show(lim(f2(x),x=-2,dir='right')) 
show(lim(f2(x),x=-1,dir='left')) 
show(lim(f3(x),x=-1,dir='right')) 
show(lim(f3(x),x=1,dir='left')) 
show(lim(f4(x),x=1,dir='right')) 
show(lim(f1(x),x=-4,dir='right')) 
show(lim(f4(x),x=3,dir='left')) 
plot(f,-4,3,aspect_ratio=1) 