#MrG 2015.0416 UNIT304: Parametric Trajectories!
show("#1) x(t)=0, y(t)=-16*t^2, y(0)=0 is the top of a well")
show("#1) You trip into a well which is 1600 ft deep, find t such that y(t)=-1600.")
show("How fast are you falling when you hit the bottom?")
var('t')
y(t)=-16*t^2;show("y(t)= ",y(t))
yp(t)=diff(y(t),t);show("y'(t)= ",yp(t))
solve(y(t)==-1600,t)
show("yp(10)=",yp(10))
show("")

show("#2a) You are a cannon ball: x(t)=0, y(t)=160*t-16*t^2.")
show("#2a) How high do you go and how long does it take to get there?")
y(t)=160*t-16*t^2;show("y(t)=",y(t))
yp(t)=diff(y(t),t);show("y'(t)= ",yp(t))
show(solve(yp(t)==0,t))
show("y(5)=",y(5))
show("")

show("#2b) You are a cannon ball: x(t)=0, y(t)=160*t-16*t^2.")
show("#2b) When are you 256 ft off the ground? How fast are you going?")
show(solve(y(t)==256,t))
show("y'(2)=",yp(2))
show("y'(8)=",yp(8))

show("83AB3: x(t)=t^3-6*t^2+9*t+11")
show("83AB3: Find x'(0) and solve for t such that x'(t)=0")
show("83AB3: When is the particle moving to the left?")
x(t)=t^3-6*t^2+9*t+11;show("x(t)=",x(t))
xp(t)=diff(x(t),t);show("x'(t)=",xp(t))
show("x'(0)=",xp(0))
show(solve(xp(t)==0,t))
plot([x(t),xp(t)],0,4)