#MrG 2018.1012 UNIT410 What Is Implicit Differentiation?
show("#1992 AB 4a: implicitly differentiate x^2+y^2==15^2 wrt time")
var('t')
x=function('x')(t)
y=function('y')(t)
ans=diff(x^2+y^2-15^2)
show(ans)
show(solve(ans,diff(x)))
show(solve(ans,diff(y)))
show("")
show("#1992 AB 4b: implicitly differentiate A=x*y/2 wrt time")
ans=diff(x*y/2)
show(ans)
show(solve(ans,diff(x)))
show(solve(ans,diff(y)))