#MrG 2015.0416 UNIT303: Trig Rules!
f(x)=sin(x);show("f(x)=",f(x))
show("f'(x)=",diff(f(x)))
f(x)=cos(x);show("f(x)=",f(x))
show("f'(x)=",diff(f(x)))
f(x)=tan(x);show("f(x)=",f(x))
show("f'(x)=",diff(f(x)).simplify_trig())
f(x)=1/tan(x);show("f(x)=",f(x))
show("f'(x)=",diff(f(x)).simplify_trig())
f(x)=1/cos(x);show("f(x)=",f(x))
show("f'(x)=",diff(f(x)).simplify_trig())
f(x)=1/sin(x);show("f(x)=",f(x))
show("f'(x)=",diff(f(x)).simplify_trig())