#MrG 2018.1002 UNIT 402: 1st & 2nd Derivative Tests
show("#1) f(x)=(x-1)*(x-2)*(x-3)*(x-4)*(x-5)")
show("#1) expand, find 1st derivative, find 2nd derivative")
show("#1) when is f increasing, when is f decreasing?")
show("#1) when is f concave down, when is f concave up?")
show("#1) what are the critical points of f'?")
show("#1) where are the mins and maxs of f(x)?")
f(x)=(x-1)*(x-2)*(x-3)*(x-4)*(x-5)
show(f(x))
show(expand(f(x)))
g(x)=diff(f(x),x)
show(g(x))
show(expand(g(x)))
h(x)=diff(g(x),x)
show(h(x))
show(expand(h(x)))
p1=plot(f(x),1,5,color='red')
p2=plot(g(x),1,5,color='green')
p3=plot(h(x),1,5,color='blue')
show(p1+p2+p3)