#MrG 2018.0912 UNIT 205: Differentibility I
show("#1) UNIT 205: Does continuity imply differentiability? ")
var('h') 
f(x)=abs(x) 
g(x)=lim((f(x+h)-f(x))/h,h=0) 
p1=plot(f(x),color='red') 
p2=plot(g(x),color='green') 
(p1+p2).show(aspect_ratio=1) 
show("")

show("#2) UNIT 205: Does differentiability imply continuity? ")
f(x)=(x+2)*(x-1)/(x-1) 
show(f(x)) 
p1=plot(f(x),-3,1,color='red') 
p2=plot(f(x),1,3,color='green') 
(p1+p2).show(aspect_ratio=1) 
show("")

show("#3) UNIT 205: Find f'(x) given f(x)=abs(x) ")
f(x)=abs(x) 
g(x)=diff(f(x),x) 
show(f(x)) 
show(g(x)) 
show(g(-2)) 
show(g(3)) 
show("")

show("#4) UNIT 205: Find f'(x) given f(x)=sqrt(x^2) ")
f(x)=sqrt(x^2) 
g(x)=diff(f(x),x) 
show(f(x)) 
show(g(x)) 
show(g(-2)) 
show(g(3)) 