#MrG 2018.1009 UNIT404 1st & 2nd Derivative Tests
show("#1) 70AB3")
show("#1) f(x) = x^(4/3)+4*x^(1/3)")
show("#1a) where are all points of horizontal and vertical tangency?")
f(x) = x^(4/3)+4*x^(1/3)
g(x) = diff(f(x),x)
show(f(x))
show(g(x).canonicalize_radical())
show("#1b) find abs max and min on the closed interval [-8,8]")
show(f(-8))
show(f(-1))
show(f(0))
show(f(8))
show("#1c) find all points of inflection")
h(x)=diff(g(x),x)
show(h(x).canonicalize_radical())
show(solve(h(x)==0,x))